### PR TITLE
Mobile first

### PR DESCRIPTION
**Pull request by noelfoka**
In this branch, I did:

- [ ] Add the header section
- [ ] Add a section who have class="head flex".
- [ ] Create an images folder and add images in.
- [ ] configure linters

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @noelfoka, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the README file is not complete. Please use the [Microverse template](https://github.com/microverseinc/readme-template).

- [ ] In the case of README consider not leaving out any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  Recording 2023-02-14 at 12 52 20 (5)	  | image |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by noelfoka** [comment]
I modify readme file

**Comment by noelfoka** [comment]
I did add future features in readme file

**Comment by topeogunleye** [comment]
> I did add future features in readme file

@noelfoka, Kindly be notifies that your README file was empty with nothing in it

**Review by abdallahmalima — CHANGES_REQUESTED** [review]
Hi @noelfoka , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Highlights
- Correct use of the `header` tag✔
- Correct use of the `nav` tag
- Nice design✔
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
